language: node_js
node_js: "11"
os:
- linux
- osx
- windows
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
    
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell Install-WindowsFeature Net-Framework-Core && cinst -y wixtoolset fi;

install:
- npm install
- npm update

script:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm run make-mac; else npm run make; fi; 
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./**/*.zip
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
    - /v\d+\.\d+.\d+/