language: node_js
node_js: "11"
os:
- linux
- osx
- windows
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

install:
- npm install
- npm update

script:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm run make-mac; else npm run make; fi; 
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi
